# Using NumPy

## What is NumPy?

advantages to python lists, how loops are done, in general, types, fix size


NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases\[[1](https://numpy.org/)\].s


Here, we describe aspects of N-d array computation that are within scope for NumPy development. This is not an aspirational definition of where NumPy should aim, but instead captures the status quo—areas which we have decided to continue supporting, at least for the time being.

* In-memory, N-dimensional, homogeneously typed (single pointer + strided) arrays on CPUs

  * Support for a wide range of data types
  
  * Not specialized hardware such as GPUs

  * But, do support wide range of CPUs (e.g. ARM, PowerX)

* Higher level APIs for N-dimensional arrays

  * NumPy is a de facto standard for array APIs in Python

  * Indexing and fast iteration over elements (ufunc)

  * Interoperability protocols with other data container implementations (like __array_ufunc__).

* Python API and a C API to the ndarray’s methods and attributes.

* Other specialized types or uses of N-dimensional arrays:

  * Masked arrays

  * Structured arrays (informally known as record arrays)

  * Memory mapped arrays

  * Historically, NumPy has included the following basic functionality in support of scientific computation. We intend to keep supporting (but not to expand) what is currently included:

  * Linear algebra

  * Fast Fourier transforms and windowing

  * Pseudo-random number generators

  * Polynomial fitting

* NumPy provides some infrastructure for other packages in the scientific Python ecosystem:

  * numpy.distutils (build support for C++, Fortran, BLAS/LAPACK, and other relevant libraries for scientific computing

  * f2py (generating bindings for Fortran code)

  * testing utilities

* Speed: we take performance concerns seriously and aim to execute operations on large arrays with similar performance as native C code. That said, where conflict arises, maintenance and portability take precedence over performance. We aim to prevent regressions where possible (e.g., through asv).

## Creating arrays

So, the effort of NumPy is providing all operations for arrays and handling N-dimensional arrays ("ndarray") as effective and near to the hardware as possible.
Let us start with just creating some ndarrays

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1.0, 2.0, 11.0, 22])
c = np.array([np.pi, 0, 0.0, 2])
d = np.array([np.pi, 0, 0.0, 2], dtype=int)
e = np.array([[2, 4], [np.cos(np.pi/2), 3], [1, 2], [3, 4]])
f = np.array([[2, 4],
             [np.cos(np.pi/2), 3],
             [1, 2],
             [3, 4]])
g = np.array([1, 2+2j, 3], dtype=complex)

Every userinitialized ndarray in NumPy needs to be enclosed in square brackets ``[ .... ]``. The square brackets indicates NumPy, how the shape and dimensions of the ndarray is going to be. NumPy provides a couple of methods for creating generic ndarrays, like filling each elements with zeros, ones, diagonal entries or linear spaced values or constant value filled matrices.

### "Ones" ndarray
To create ndarrays filled with only "1", NumPy provides its method ``np.ones()``. To alter the shape of the ones-ndarray, it just needs to pass the shape information as arguement to the ones method. For example, 2 rows and 4 columns are desired, the call would look like

In [2]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### "Zeros" ndarray
In general, an ndarray created by the zeros method works like using the ones method, except from filling the ndarray with zeros instead of ones.

In [3]:
np.zeros((6, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### "Eye" ndarray
The eye ndarray method creates identity ndarrays or asymmetric ndarrays filled with zeros, except a desired diagonal, which is filled with ones.

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.eye(5, 6, 3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### "linspace" ndarray

### "Full" ndarray

In [6]:
shape = (5, 3)
np.full(shape, 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

It is possible to retrieve many ndarray attributes of created ndarrays, a classy way would be just to display the values of ndarrays. Have a try yourself and generate output for other ndarrays apart from ``a``.

In [7]:
a

array([1, 2, 3])

For better readability, it is also possible to use the ``print()`` method.

In [8]:
print(a)

[1 2 3]


That was a pretty obvious call, this is nothing new because all variables can be checked like that in python. Other retrievable information are ``shape``, ``ndim``, ``size`` and ``dtype``. ``shape`` gives information about the length of each dimension, ``ndim`` tells the user how many dimensions the ndarray exists, ``size`` gives the count of how many elements the ndarray contains and ``dtype`` returns the datatype of the values in the ndarray.

In [9]:
e.shape

(4, 2)

In [10]:
e.ndim

2

In [11]:
e.size

8

In [12]:
e.dtype

dtype('float64')

# References